### ISSUE TITLE
Mejora README

### ISSUE THREAD

**Issue by edgarshurtado** [fchispano/recursos#10]
Si tenéis cualquier idea de cómo mejorar el README será bien recibida.

Los cambios que vaya haciendo se pueden ver [aquí](https://github.com/edgarshurtado/fchispano-recursos/tree/readme)

**Comment by soulchainer** [comment]
De hecho yo estoy «en ello» xD. Sólo que no ahora mismo y para algo tan nimio no puse una issue. Estoy esperando a que me resuelvan un ticket de soporte técnico, para hacer un par de cambios :þ.

**Comment by soulchainer** [comment]
Que por cierto, @edgarshurtado... Eso es tu fork, me acabo de dar cuenta ahora...
Para la próxima, manda una Pull Request ^_^U (o pushealo directamente, tú que puedes, si estás seguro).

Cuando alguien trabaja en una issue (que un tercero puso ahí para que se resuelva), pues lo dice, en plan: oye, estoy resolviendo este problema, preocupaos de resolver otros. Y cuando lo tiene hecho, pues manda la PR. Eso si el problema es muy grande. Y tampoco necesariamente (aunque se arriesga a que otro mande una PR entre tanto).
Las ideas bien recibidas de cualquier persona... son pull requests.
La idea no es que te digan lo que puedes añadir tú en tu fork para después hacer tú la PR y tal. La idea es que si alguien ve como mejorar algo, haga directamente la PR ^_^U.

No necesitas asignarte el mejorar el `README.md`, no estás trabajando en un código que vaya a generar múltiples conflictos si otra persona lo toca al mismo tiempo ;).

Yo iba  a hacer unos cambios ahora y me encuentro con que no has pusheado ni hecho PR de lo anterior (que yo creía que sí), pues lo que hago es que los hago directamente y ya, si quieres cambiar algo, lo cambias, que es lo que se suele hace y no hay problema con ello ;). Si quieres asignarte algo, puedes asignarte https://github.com/fchispano/recursos/issues/9

**Comment by edgarshurtado** [comment]
Ok, aunque también es que estoy haciendo pruebas para saber un poco cómo va flujo de trabajo en esto xD
