### ISSUE TITLE
Nuevo comando `git show`

### ISSUE THREAD

**Issue by edgarshurtado** [fchispano/recursos#24]
### Descripción

He visto que ha habido una re-estructuración del archivo, por lo que no tengo claro dónde sería el mejor sitio para el siguiente comando. Se trata de un comando para listar los archivos modificados por un commit.

`git show --pretty="" --name-only <commit>`

He pensado que tal vez tendría que abrir otro apartado para los comandos **show**. ¿Qué pensáis?

#### Fichero afectado (opcional)
git_cheatsheet.md

**Comment by soulchainer** [comment]
Ummm... Veo que ya hay otro comando `git show` en [Other info](https://github.com/fchispano/recursos/blob/master/git_cheatsheet.md#other-info-).
Igual debería ir ahí.

En cualquier caso, de no ser así, tendrías que mover también ese `git show` a la nueva ubicación (o renombrar la actual, no sé). Y la sección a la que se moviera debería ser una con un título descriptivo de la funcionalidad. Es decir: el documento está estructurado según funcionalidad, no nombre del comando. Para que quién lo vea (aunque terminamos siendo tú y yo xD) sepa lo que hacen, en general, ese grupo de comandos mirando el título.

**Nota**: ya que vas a editar, aprovecha y cambia la flechita `->` del otro show, por `→` xD. Creo recordar que ya me lo comentaste, pero se me olvidó xD.

**Comment by edgarshurtado** [comment]
Vale, de momento lo añado en *Other info* y edito esa flechita =).
