### ISSUE TITLE
Pruebailassue

### ISSUE THREAD

**Issue by OldGordon** [fchispano/recursos#7]
Propuesta: 
Brain Storming sobre aplicaciones web.
P.e. Toni : App que reconozca canción y autor , y sincronice la letra para hacer karaoke live XD

**Comment by soulchainer** [comment]
Hola, @OldGordon.

Como ya he comentado por **Gitter**, creo que el propio **Brainstorming** y la lista de ideas en sí misma debería de ser una página en la wiki de un repositorio.
Es más: propongo y creo que se ha de hacer un repositorio nuevo específicamente para albergar una wiki para la organización, con cosas generales. Ya que ahora mismo esta issue está en el repositorio de **recursos** y esa idea no cuaja demasiado con la idea de recursos ;).
En esa wiki general podríamos poner cosas como el **how contribute**, explicar de qué va la organización, quienes son los miembros, los equipos que tiene (cuando los tenga), etc etc... Porque por cosas que explicar no será.

¿Qué opinas, @edgarshurtado?

**Comment by edgarshurtado** [comment]
Como idea no lo veo mal, ya que supongo que las ideas para app que dice @OldGordon serían para empezar un desarrollo conjunto los miembros de **FCH**. No? Lo que yo estos pasos no sé si los daría más poco a poco. En el pasado ya he intentado hacer proyectos con más gente con todo bien estructurado, y muy completos. Por desgracia, estaban tan completos esos proyectos que intimidaban a la gente y acababan por no tener participación.

Por lo tanto si lo veis bien por mí estupendo, pero personalmente yo dejaría la organización en su mínima expresión (un único repositorio) para que la gente pierda el miedo y vaya contribuyendo. Y con el tiempo ya nos mareamos con **wikis**, más **repos**, etc. El nombre del repositorio lo podriamos cambiar para que represente más esta idea de *cajón de sastre*

**Comment by freecodehispano** [comment]
Pues sí, supongo que se puede hacer en un sólo repo, @edgarshurtado. Aunque más que *cajón de sastre* algo así será *cajón desastre* :þ.
Y luego, cuando haya que organizarlo... Normalmente es mejor partir de algo medio organizado.

Pero bueno, para algo como lo que plantea, sirve de momento un documento en markdown, con checklists.

Tal como lo ha planteado @OldGordon yo he entendido que lo que el propone es una

# Lista de ideas de aplicaciones web a realizar para mejorar tu portafolio

Más que algo para empezar un desarrollo conjunto con los miembros de **FCH** (que esa es otra idea a tener en cuenta a futuro, por supuesto) :D.

**Comment by edgarshurtado** [comment]
Pues eso de momento creamos un documento md para cada cosa que sea distinta y con el paso del tiempo ya vamos viendo (pd, a mí siempre me hizo más gracia lo de *cajón de sastre* porque era como un juego de palabras xD)

**Comment by OldGordon** [comment]
La verdad es que me refería a lista de ideas que surgen y no las apuntamos en ningún lado y que pueden inspirar al grupo  , pues si, a mejorar el portfolio o para empezar un proyecto nuestro o para lo que sea . Un proyecto empieza con una idea y luego que progrese o no es otra historia .

**Comment by edgarshurtado** [comment]
Pero para eso no sé si estaría mejor que cada uno tenga su lista. Ya que si todos vamos poniendo las ideas en bruto que tengamos no sé si acabaremos teniendo un archivo inmanejable.

Lo que sí que se podría publicar aquí serían proyectos que busquen a colaboradores.

Creo que lo mejor sería hacer una encuesta a ver lo que opinan los demás.

**Comment by soulchainer** [comment]
Sí. A ver, yo la idea (inicial), la veo bien en los términos que expuse antes.
Pero vamos, de acuerdo contigo, @edgarshurtado, yo lo entendí como una lista **breve** de algunos proyectos genéricos que se pueden proponer para alguien que no sepa que hacer para mejorar su portfolio. Vamos... justo algo como lo que ya hace Free Code Camp:
- Crea un juego de Simon
- Crea una aplicación que use la API de la Wikipedia
- Crea una aplicación que muestre una serie de citas celebres

xD. Obviamente, si es en plan de poner una lista de ideas larguísima, desde luego que es mejor que cada uno la tenga (y la tiene).
Lo de proyectos de colaboración es interesante. A futuro, pero interesante. Aunque considero que eso no sería algo que debiera ir en un repo. Porque no es un foro, ni un panel de anuncios. Eso debería ir en una plataforma más dinámica. Como en una github pages, cuando la hagamos. Se podría hacer una web app para eso :þ. Pero más adelante, que vamos muy rápido xD.

**Comment by edgarshurtado** [comment]
Entonces al final qué? porque ya me he perdido jeje

**Comment by soulchainer** [comment]
Pues al final, @edgarshurtado, yo creo que realmente si es una lista de ideas... esto pertenece más al ámbito foro de discusión.  Es algo que se repite mucho: alguien diciendo que le den ideas de qué sitios sencillitos/medio complejos puede realizar para mejorar su portfolio.

A ver, que la idea no es que sea mala, pero un brainstorming  y cosas de este estilo no suelen hacerse en un documento escrito de este tipo. Suele hacerse en la típica página de preguntas y respuestas como [quora](https://www.quora.com), en un foro o en un chat. Yo creo que esta issue se debería cerrar, pero no quería hacerlo sin discutirlo antes.

Yo esas ideas que surgen y no las apuntamos en ningún lado... si las apunto ^_^U.
Si es para proyectos de colaboración, eso tampoco se suele apuntar. Se discute en una plataforma viva (chat/foro) y cuando se llega a un acuerdo, se hace (esta organización ha surgido así). Luego, otra cuestión es que ya tengas el proyecto y pidas colaboraciones (eso es el `CONTRIBUTING.md`).

Decidme si estamos de acuerdo o no.

**Comment by OldGordon** [comment]
Vamos a ver, el primer mensaje que puse en esta "issue" era para ir poniendo algo y puse algo que se me ocurrió y porque Edgar me dijo que era el sitio para ponerlo. Si no es adecuado ni el contenido ni el continente pues se borra y listo . Yo tengo una libreta fantástica donde apunto cualquier cosa que se me ocurre , ya sea de negocios o desarrollo web. Solo era para empezar a animar . Como tener ideas es algo primordial en cualquier recurso  pues .. eso XD Si no os gusta se borra y todos contentos. No big deal.

**Comment by soulchainer** [comment]
De buen rollito, @OldGordon :). Es que me daba palo cerrarlo sin más y tal, y ya que estábais animados...
Tienes toda la razón en que tener ideas es algo primordial. Pero igual no te entendí o no lo explicaste lo suficientemente claro antes. Yo lo que entendí es que proponías que se hiciera un archivo con un listado de posibles ideas. Y para brainstorming ya tenemos Gitter. You know what? Acabo de crear un [nuevo canal, llamado Brainstorming](https://gitter.im/fchispano/Brainstorming), específicamente para ello. Porque el general es para lo que es, un lugar de esparcimiento y charlar de todo. ¿Os parece oportuno?
Si es así, cierro esto.

**Comment by edgarshurtado** [comment]
@OldGordon Puede que yo tampoco te entendiera xD. También pensaba que querías registrarlo en un archivo del repo :sweat_smile:
