### ISSUE TITLE
Fichero para ir añadiendo enlaces a recursos

### ISSUE THREAD

**Issue by edgarshurtado** [fchispano/recursos#9]
Creo que va siendo hora de crear al menos un único fichero **MarkDown** para que vayamos copiando links a recursos que nos parecen útiles y que recomendamos. Algo parecido a lo que hago en [mi lista personal](https://github.com/edgarshurtado/Knowledge-Log/blob/master/to-do-list.md).

**Comment by soulchainer** [comment]
Si estás haciéndolo, @edgarshurtado, deberías ir a [waffle](https://waffle.io/fchispano/recursos), asignarte esta tarea a ti y arrastrarla a **In Progress**, para que los demás sepan que estás haciendo eso y no duplicar esfuerzos :3.

**Comment by edgarshurtado** [comment]
No, de momento lo que estoy haciendo es mejorar un poco el README que lo veo muy pobre como está ahora
